-- DROP DATABASE
DROP DATABASE IF EXISTS guttman_202db_assign4;

-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS guttman_202db_assign4
CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- USE DATABASE
USE guttman_202db_assign4;
